### ISSUE TITLE
Lista de resultados

### ISSUE THREAD

**Issue by rafaeldcfarias** [tdurand/mapafortaleza#17]
Poderia haver uma lista de resultados após pesquisar por destino, ele só apresenta o primeiro resultado.

**Comment by tdurand** [comment]
Si seria bom, concordo

**Comment by regismesquita** [comment]
Boa idéia, thibault se quiser posso implementar isso esse fds...

---

RDSM

**Comment by tdurand** [comment]
Como quiser, o projeto é o seu tambem, só deixa me dar olhada antes de push
no gh-pages.

Abraço

2013/2/19 Regis David Souza Mesquita notifications@github.com
