### ISSUE TITLE
Etufor data link is broken

### ISSUE THREAD

**Issue by bplmp** [tdurand/mapafortaleza#27]
The link for the Etufor data on the README file is broken. This is the most recent archived version of it I could find and it also seems incomplete: https://web.archive.org/web/20120621142656/http://www.fortaleza.ce.gov.br/etufor/index.php?option=com_content&task=view&id=278

**Comment by felipsmartins** [comment]
Not sure about old link content but Etufor has crated a new open data catalogue: 
http://dados.fortaleza.ce.gov.br/portal/

**Comment by tdurand** [comment]
Muito ruim isso, mandei ums 10 correo e eles nao quer disponibilizar datos mais recente que o arquivo do 2015.... 

O Moovit e o google map sim tem datos recente...

**Comment by ti4luciano** [comment]
Hello everyone, I would like to contribute to the project, (I work a little while with development but I would like to help in some way, even if it disturbs ETUFOR) I saw that it is off, is this situation # 27? I am an admirer and loyal user of this project.

**Comment by tdurand** [comment]
Hi, the project is kind of dead, I actually need to set up a link to use the moovit app, which became very good in fortaleza
