### ISSUE TITLE
Add a link to add a marker from the geo position of the user

### ISSUE THREAD

**Issue by tdurand** [tdurand/mapafortaleza#9]

**Comment by mariovalney** [comment]
Adicionei um segundo botão abaixo de "Adicionar Ponto" que ao ser acionado acrescenta um marker com a geolocalização do usuário, se possível, senão um alert() avisando. E dá um name para o marker com o texto 'EU'.

Além disso só mexi um pouco no CSS.
Espero que curta.

**Comment by tdurand** [comment]
Belez, ja comparti a novidade nas redes sociais, muito obrigado, faz tempo que ja não to morando em Fortaleza, então o projecto fica meio morte. Muito feliz quando alguém participa.
